from .form_paciente import PacienteForm
from .form_responsavel import ResponsavelForm
from .form_informacoes_complementares import InformacoesComplementaresForm
from .form_devolutiva import DevolutivaForm
from .form_encaminhamento import EncaminhamentoForms
from .form_evolucao_diaria import EvolucaoDiariaForm
from .form_reunioes_externas import ReunioesExternasForms
from .form_supervisao_multidisciplinar import SupervisaoMultiprofissionalForm
