# Generated by Django 4.2.7 on 2023-12-10 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(blank=True, max_length=255)),
                ('paciente_dt_nasc', models.DateField(blank=True)),
                ('paciente_responsavel_nome', models.CharField(blank=True, max_length=255)),
                ('paciente_responsavel_email', models.EmailField(blank=True, max_length=254)),
                ('paciente_responsavel_contato', models.CharField(blank=True, max_length=255)),
                ('paciente_responsavel_cpf', models.CharField(blank=True, max_length=255)),
                ('paciente_exams', models.FileField(upload_to='files/')),
                ('paciente_foto', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanceiroTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_financeiro_tipo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanceiroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_financeiro_valor', models.CharField(blank=True, max_length=255)),
                ('registro_financeiro_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('registro_financeiro_funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('registro_financeiro_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EAEE.registrofinanceirotipomodel')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteRegistroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_registro_queixa', models.TextField()),
                ('paciente_registro_procedimento_avaliativo', models.TextField()),
                ('paciente_registro_observacao_clinica', models.TextField()),
                ('paciente_registro_resultado', models.TextField()),
                ('paciente_registro_conclusao', models.TextField()),
                ('paciente_registro_dt_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('paciente_registro_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAEE.pacientemodel')),
                ('paciente_registro_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicado_mensagem', models.TextField()),
                ('comunicado_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('comunicado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
