# Generated by Django 4.2.7 on 2023-12-26 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('paciente_foto', models.ImageField(upload_to='paciente/fotos/')),
                ('paciente_dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('paciente_identidade', models.FileField(upload_to='paciente/documentos/identificacao', verbose_name='Identidade')),
                ('paciente_exame', models.FileField(upload_to='paciente/documentos/exames', verbose_name='Exame_1')),
                ('paciente_exame_2', models.FileField(upload_to='paciente/documentos/exames', verbose_name='Exame_2')),
                ('paciente_exame_3', models.FileField(upload_to='paciente/documentos/exames', verbose_name='Exame_3')),
                ('paciente_dt_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeVinculoComPacienteModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_filiacao_nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('paciente_filiacao_tipo_vinculo', models.CharField(max_length=255, verbose_name='Tipo de Vinculo')),
                ('paciente_filiacao_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('paciente_filiacao_dt_nascimento', models.DateField()),
                ('paciente_filiacao_contato_telefone_pessoal', models.CharField(max_length=255, verbose_name='Contato Pessoal')),
                ('paciente_filiacao_contato_telefone_empresa', models.CharField(max_length=255, verbose_name='Contato Profissional')),
                ('paciente_filiacao_cpf', models.CharField(max_length=255, verbose_name='Identidade')),
                ('paciente_filiacao_nacionalidade', models.CharField(max_length=255, verbose_name='Nacionalidade')),
                ('paciente_filiacao_profissao', models.CharField(max_length=255, verbose_name='Profissão')),
                ('paciente_filiacao_estado_civil', models.CharField(max_length=255, verbose_name='Estado Civil')),
                ('paceinte_filiacao_endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('paceinte_filiacao_comprovante_residencia', models.FileField(upload_to='files/filiado/comprovante_de_residencia', verbose_name='Comprovante de Residencia')),
                ('paciente', models.ManyToManyField(to='EAEE.pacientemodel', verbose_name='Responsável')),
            ],
        ),
    ]
