# Generated by Django 4.2.7 on 2024-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAEE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamentomodel',
            name='para',
        ),
        migrations.AlterField(
            model_name='encaminhamentomodel',
            name='sintese',
            field=models.TextField(verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='acorda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='alimento_atual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='altura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='apgar1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='apgar5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='baba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='condicoes_emocionais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='cuidados_parto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='dorme_sozinho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='escola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='esfincteres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='fala_dormindo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='fatos_marcantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='fobias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='gravidez',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='horario_de_dormir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='leite_marterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='mora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='parto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='peso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='pos_parto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='recebe_ajuda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='semanas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='sono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='succao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='turno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='usou_mamadeira',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_exame',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Exame_1'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_exame_2',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Exame_2'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_exame_3',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Exame_3'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_foto',
            field=models.ImageField(blank=True, null=True, upload_to='paciente/fotos/'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_identidade',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/identificacao', verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='paciente_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paceinte_filiacao_cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paceinte_filiacao_comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='files/filiado/comprovante_de_residencia', verbose_name='Comprovante de Residencia'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paceinte_filiacao_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_contato_telefone_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Profissional'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_contato_telefone_pessoal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Pessoal'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_cpf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_estado_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_nacionalidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_profissao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='tipodevinculocompacientemodels',
            name='paciente_filiacao_tipo_vinculo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Vinculo'),
        ),
    ]
