# Generated by Django 4.2.7 on 2024-01-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAEE', '0002_remove_encaminhamentomodel_para_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofinanceiromodel',
            options={'verbose_name': 'Financeiro', 'verbose_name_plural': 'Financeiro'},
        ),
        migrations.AlterField(
            model_name='devolutivamodel',
            name='dt_devolutiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='devolutivamodel',
            name='para',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='devolutivamodel',
            name='sintese',
            field=models.TextField(blank=True, null=True, verbose_name='Síntese'),
        ),
        migrations.AlterField(
            model_name='encaminhamentomodel',
            name='dt_devolutiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='encaminhamentomodel',
            name='sintese',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='evolucaodiariamodel',
            name='dt_devolutiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='evolucaodiariamodel',
            name='sintese',
            field=models.TextField(blank=True, null=True, verbose_name='Síntese'),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='acompanhamento_fonoaudiologico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='acompanhamento_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='alfabetizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='articulacao_palavras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='atencao_por_tempo_significativo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='autonomia_dormir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='compreende_comandos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='comunicacao_atual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='contato_visual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='doencas_alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='encaminhado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='exames_fonoaudiologicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='expectativa_do_acompanhamento_fonoaudiologico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='familiar_dificuldades_na_fala',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='gosta_de_brincar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='hobby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='horas_de_sono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='idade_comecou_escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='interage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='mamadeira_chupeta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='materia_mais_gosta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='prende_atencao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='primeiras_palavras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='quando_andou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='quando_balburciou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='quando_comecou_sentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='quando_comeu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='quando_engatinhou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='queixa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='regressao_linguistica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='relacionamento_criancas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='relacionamento_pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='teste_orelinha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonoaudiologia',
            name='tratamento_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='aceita_seguir_comandos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='acompanhamento_psicologico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='acorda_vai_para_cama_dos_pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='adoece_facilmente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='algum_membro_ja_fez_acompanhamento_psicologico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='assiste_enquanto_come',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='atitude_dos_pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='atitudes_desse_habito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='baste_cabeca_na_parede',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='brinca_sozinho_ou_grupo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='brincadeiras_brinquedo_favorito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='como_se_alimenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='comportamento_roer_unhas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='curiosidade_sexual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='dificuldades_desfraude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='dorme_sozinho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='encaminhamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='estranha_mudancas_ambiente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='gosta_de_musicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='higiene_sozinho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='horario_para_refeicoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='humor_habitual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='idade_desfralde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='idade_higiene_sozinho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='idade_operado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='informacoes_sexuais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='internado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='motivo_internação',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='numero_irmaos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='objeto_para_dormir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='operado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='personalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='problema_na_fala',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='queixa_psicologica_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='reacao_nascimento_irmao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='refeicoes_em_familia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='relacionamento_colegas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='relacionamento_familia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='relacionamento_irmaos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='relacionamento_pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='relacionamento_professores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='reprovou_na_escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='seletividade_alimentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='tratamento_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='troca_letras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='urina_na_cama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='abotoa_roupas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='amarra_cadarco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='anda_bicicleta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='andou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='atividades_juntos_no_tempo_livre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='brincadeiras_sozinho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='como_era_bebe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='como_realiza_atividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='como_se_sai_nas_brincadeiras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='dificuldades_no_ambiente_escolar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='engatinhou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='fez_uso_do_andaja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='ficou_de_pe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='gosta_escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='gosta_professores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='idade_andou_bicicleta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='idade_frequentou_escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='idade_que_firmou_a_cabeca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='nao_gosta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='outras_preferencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='pega_obj_pequenos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='pratica_esportes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='preferecia_pela_mao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='preferencias_brinquedos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='relacao_colegas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='sentou_sem_apoio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicomotricidade',
            name='troca_roupas_sozinho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='ajuda_em_casa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='anda_bicicleta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='antecedentes_com_dificuldade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='brinquedos_favorito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='censurado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='como_foi_adaptacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='corporalmente_desenvolto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='dificuldades_aprendizagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='fala_compreensivel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='falta_assiduo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='fragilidades_evidentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='gosta_desenhar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='horas_livres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='idade_que_comecou_a_frequentar_escola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='motivado_escola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='organizado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='potencialidades_marcantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='precisa_ajuda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='predilecao_matematica_portugues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='queixas_comuns_escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='ralacao_professores_colegas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='realiza_atividades_com_satisfacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='reprovou',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicopedagogia',
            name='uso_de_eletronicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reunioesexternasmodel',
            name='dt_devolutiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reunioesexternasmodel',
            name='participantes',
            field=models.TextField(blank=True, null=True, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='reunioesexternasmodel',
            name='sintese',
            field=models.TextField(blank=True, null=True, verbose_name='Síntese'),
        ),
        migrations.AlterField(
            model_name='supervisaomultiprofissionalmodel',
            name='dt_devolutiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='supervisaomultiprofissionalmodel',
            name='especialista',
            field=models.TextField(blank=True, null=True, verbose_name='Especialistas'),
        ),
        migrations.AlterField(
            model_name='supervisaomultiprofissionalmodel',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='supervisaomultiprofissionalmodel',
            name='plano_de_acao',
            field=models.TextField(blank=True, null=True, verbose_name='Plano de Ação'),
        ),
    ]
