# Generated by Django 4.2.7 on 2024-01-05 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EAEE', '0003_comunicadomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanceiroTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_financeiro_tipo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanceiroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_financeiro_valor', models.CharField(blank=True, max_length=255)),
                ('registro_financeiro_destino', models.CharField(blank=True, max_length=255)),
                ('registro_financeiro_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('data_filtro', models.DateField(blank=True, null=True)),
                ('registro_financeiro_funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('registro_financeiro_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EAEE.registrofinanceirotipomodel')),
            ],
        ),
    ]
