# Generated by Django 4.2.7 on 2024-01-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAEE', '0003_alter_registrofinanceiromodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolutivamodel',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='encaminhamentomodel',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='evolucaodiariamodel',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='reunioesexternasmodel',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='supervisaomultiprofissionalmodel',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='paciente/documentos/exames', verbose_name='Anexo'),
        ),
    ]
