# Generated by Django 4.2.7 on 2024-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAEE', '0004_registrofinanceirotipomodel_registrofinanceiromodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanceiromodel',
            name='registro_financeiro_dt',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
