# Generated by Django 4.2.7 on 2024-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAEE', '0005_alter_registrofinanceiromodel_registro_financeiro_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanceiromodel',
            name='registro_financeiro_dt',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
